### ISSUE TITLE
List firmware

### ISSUE THREAD

**Issue by Smurf81** [Jetup13/Retroid-Pocket-3-Plus-Wiki#1]
Hello

do you have a list of firmware for the RP3+ ? Mine is in version 86 but i see a video with a new firmware in 218 and i can't find it. Do you have it ?

**Comment by Jetup13** [comment]
You mean the OTA update? [That was pulled by Retroid](https://www.reddit.com/r/retroid/comments/13f5a04/update_regarding_the_latest_ota) as it was causing problems for some devices.
